### PR TITLE
add conf template

### PR DESCRIPTION
**Pull request by Nicole00**

### CODE REVIEW

**Comment by Nicole00** [comment]
@MuYiYong Please list more datasources that we need to give the config templates. In this pr, just provide config template for csv and hive for both client import and sst import.

**Comment by MuYiYong** [comment]
> @MuYiYong Please list more datasources that we need to give the config templates. In this pr, just provide config template for csv and hive for both client import and sst import.
CSV on S3, HBase,Hive, MySQL,neo4j, MaxCompute，kafka, SST

**Review by MuYiYong — APPROVED** [review]
OK

**Comment by Nicole00** [comment]
> > @MuYiYong Please list more datasources that we need to give the config templates. In this pr, just provide config template for csv and hive for both client import and sst import.
> 
> CSV on S3, HBase,Hive, MySQL,neo4j, MaxCompute，kafka, SST

There are CSV, Hive, SST config templates already. I can add config template for neo4j, MaxCompute and Kafka.
But: 
* We DO NOT support S3.
* HBase datasource is not typical,  no need to provide config template.
* For MySQL, maybe JDBC is better?

**Pull request merged**
