### PR TITLE
add batch delete for nebula-exchange

### PR DESCRIPTION
**Pull request by EldinZhou**
Add batch delete for nebula-exchange with unit tests for config parsing and execute delete statements

### CODE REVIEW

**Comment by wey-gu** [comment]
Wow, @EldinZhou thanks a lot for the great work!!!

Could you please help sign the CLA?

cc @Nicole00 we have a deletion impl. now!

**Comment by EldinZhou** [comment]
Ok, no problem！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Wey Gu ***@***.***>
发送时间: Monday, July 24, 2023 2:49:40 PM
收件人: vesoft-inc/nebula-exchange ***@***.***>
抄送: Zhou Ziyi ***@***.***>; Mention ***@***.***>
主题: Re: [vesoft-inc/nebula-exchange] add batch delete for nebula-exchange (PR #151)

        - External Email -



Wow, @EldinZhou<https://github.com/EldinZhou> thanks a lot for the great work!!!

Could you please help sign the CLA?

cc @Nicole00<https://github.com/Nicole00> we have a deletion impl. now!

―

**Review by Nicole00 — DISMISSED** [review]
LGTM！Excellent job！

**Comment by Nicole00** [comment]
please check the compile error and sign cla~

**Comment by EldinZhou** [comment]
> please check the compile error and sign cla~

CLA sign done~

**Comment by EldinZhou** [comment]
> please check the compile error and sign cla~

maybe fix the error caused by typo of writeMode

**Review by Nicole00 — APPROVED** [review]

**Comment by Nicole00** [comment]
@cooper-lzy Now we can support batch delete function for exchange, the config example can be found in https://github.com/vesoft-inc/nebula-exchange/pull/151/files#diff-a55ebb9daa91e9046a352946a76fff36b82f42d2a31881983c4a57abb2b70f8d.

**Pull request merged**
